apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce # 단일 노드에서 읽고 쓰기 가능
  resources:
    requests:
      storage: 1Gi # 1기가바이트의 저장 공간 요청

---
apiVersion: v1
kind: Service
metadata:
  name: db-service # 클러스터 내에서 사용할 서비스 이름
spec:
  selector:
    app: book-review-db # 아래 Deployment의 Pod 라벨과 일치해야 함
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-review-db
  template:
    metadata:
      labels:
        app: book-review-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "bookreview"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom: # secrets.yaml에 정의된 값을 참조
                secretKeyRef:
                  name: book-review-secrets # Secret 객체 이름
                  key: POSTGRES_PASSWORD # Secret 내부의 키
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc # 위에서 생성한 PVC 이름
