name: test cd

on:
  push:
    branches:
      - feature/dockerize

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/manga-app

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd /home/${{ secrets.DEPLOY_HOST }}/book-review
            git pull origin feature/dockerize
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            # docker compose -f docker-compose.yaml pull app
            # docker compose -f docker-compose.yaml up -d --no-deps app
            docker image prune -f
